version: '3'

services:
  db:
    image: postgres:14

    environment:
      POSTGRES_USER: postgres
      # Password removed
      POSTGRES_DB: relecloud
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    ports:
      - 5432:5432
      - 8000:8000

    volumes:
      - postgres-data:/var/lib/postgresql/data 
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./demo-code/Dockerfile
    depends_on:
      - db

    network_mode: service:db

volumes:
  postgres-data: