version: '3'

services:
  db:
    image: postgres:14

    environment:
      DBSERVER_USER: postgres
      DBSERVER_DB: relecloud
      DBSERVER_HOST: db
      DBSERVER_PORT: 5432

    ports:
      - 5432:5432
      - {{cookiecutter.web_port}}:{{cookiecutter.web_port}}

    volumes:
      - postgres-data:/var/lib/postgresql/data 
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./{{cookiecutter.project_slug}}/Dockerfile
    depends_on:
      - db

    network_mode: service:db

volumes:
  postgres-data: