version: '3'

services:
  db:
    image: postgres:14

    environment:
      DBSERVER_USER: postgres
      DBSERVER_DB: relecloud
      DBSERVER_HOST: db
      DBSERVER_PORT: 5432

    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d relecloud"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./{{cookiecutter.project_slug}}/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    network_mode: service:db

volumes:
  postgres-data: