[project]
name = "flaskapp"
version = "1.0.0"
dependencies = [
    "Flask==2.3.2",
    "Flask-Migrate==4.0.4",
    "Flask-SQLAlchemy==3.0.5",
    "psycopg2-binary==2.9.6",
    "SQLAlchemy==2.0.17"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"