{# db layer configurations #}
{% macro db() %}
    image: postgres:14

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: relecloud
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432  

    volumes:
      - postgres-data:/var/lib/postgresql/data 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d relecloud"]
      interval: 5s
      timeout: 5s
      retries: 5
{% endmacro %}

{% macro app_environment() %}
    {% if 'postgres' in cookiecutter.db_resource %}
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: relecloud
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
    {% endif %}
{% endmacro%}
