name: Python Format Check
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

jobs:
    checks-format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
                python-version: 3.11
                cache: 'pip'
        - name: Check Format
          run: |
                pip install ruff black
                ruff . --fix
                black . --verbose
        - name: Commit any new changes
          run: |
                if [ -z "$(git status --porcelain)" ]; then
                    echo "No changes to commit"
                    exit 0
                fi
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add .
                git commit -m "Format code"
                git push


