name: Run Playwright tests
on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'




jobs:
  # Label of the container job
  Create-Container:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: python:3.11

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: relecloud
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: |
            python -m pip install -r requirements-dev.txt
            playwright install
            playwright install-deps
      - name: Run migrations and Playwright tests
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: |
            cd demo-code
            python manage.py migrate
            python manage.py collectstatic
            python manage.py test relecloud.playwright
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DJANGO_SETTINGS_MODULE: project.settings_local
          POSTGRES_HOST: postgres
          POSTGRES_DB: relecloud
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
