[tool.ruff]
line-length = 120
select = ["E", "F", "I", "UP"]
ignore = ["D203"]

{% if cookiecutter.project_backend == "flask" %}
[tool.ruff.isort]
known-local-folder = ["flaskapp"]
{% endif %}

[tool.black]
line-length = 120

[tool.pytest.ini_options]
addopts = "-ra --cov -vv"
{% if cookiecutter.project_backend == "django" %}
DJANGO_SETTINGS_MODULE = "project.settings"
{% endif %}

[tool.coverage.report]
show_missing = true