name: Validate AZD template
on:
  push:
    branches: [ main ]
    paths:
      - "{{cookiecutter.__src_folder_name}}/infra/**"
  pull_request:
    branches: [ main ]
    paths:
      - "{{cookiecutter.__src_folder_name}}/infra/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: github.repository == 'Azure-Samples/Azure-Python-Standardization-Template-Generator'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
